name: Build project

on:
  pull_request: {}
  push: {}

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  default_Builder:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.3f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          #- Android # Build an Android .apk standalone app.
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get cached libraries
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-
      - name: Build
        uses: webbertakken/unity-builder@v0.11
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.targetPlatform }}
          path: build

  iOS_Builder:
    name: Build iOS IPA
    runs-on: macos-latest
    needs: [default_Builder]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: iOS
          path: xcode
      - name: Install XCode
        uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: '11.4' # Exact version of a Xcode version to use
          apple-id: ${{ secrets.APPLE_EMAIL }} # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.APPLE_PASSWORD }}
      - run: chmod -R 777 xcode/iOS/iOS/
      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_PASSWORD }}
      - name: Build Project
        run: |
          set -xeu
          set -o pipefail

          function finish() {
            ditto -c -k --sequesterRsrc --keepParent "${RESULT_BUNDLE_PATH}" "${RESULT_BUNDLE_PATH}.zip"
            rm -rf "${RESULT_BUNDLE_PATH}"
          }

          trap finish EXIT

          SDK="${SDK:-iphoneos}"
          SCHEME="${SCHEME:-Unity-iPhone}"
          CONFIGURATION=${CONFIGURATION:-Release}

          BUILD_DIR=${BUILD_DIR:-.build}
          ARTIFACT_PATH="build/XCode"
          RESULT_BUNDLE_PATH="${ARTIFACT_PATH}/${SCHEME}.xcresult"
          ARCHIVE_PATH=${ARCHIVE_PATH:-${BUILD_DIR}/Archives/${SCHEME}.xcarchive}
          DERIVED_DATA_PATH=${DERIVED_DATA_PATH:-${BUILD_DIR}/DerivedData}
          EXPORT_OPTIONS_FILE="Support/ExportOptions.plist"

          rm -rf "${RESULT_BUNDLE_PATH}"

          xcrun xcodebuild \
              -project xcode/iOS/iOS/Unity-iPhone.xcodeproj \
              -scheme "${SCHEME}" \
              -configuration "${CONFIGURATION}" \
              -sdk "${SDK}" \
              -parallelizeTargets \
              -showBuildTimingSummary \
              -disableAutomaticPackageResolution \
              -derivedDataPath "${DERIVED_DATA_PATH}" \
              -archivePath "${ARCHIVE_PATH}" \
              -resultBundlePath "${RESULT_BUNDLE_PATH}" \
              archive

          xcrun xcodebuild \
              -exportArchive \
              -exportOptionsPlist "${EXPORT_OPTIONS_FILE}" \
              -archivePath "${ARCHIVE_PATH}" \
              -exportPath "${ARTIFACT_PATH}/${SCHEME}.ipa"

          # Zip up the Xcode Archive into Artifacts folder.
          ditto -c -k --sequesterRsrc --keepParent "${ARCHIVE_PATH}" "${ARTIFACT_PATH}/${SCHEME}.xcarchive.zip"
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.targetPlatform }}
          path: build/XCode
