name: Publish

on:
  release: { types: [published] }
  
jobs: 
  publish:
    name: Publish the app
    runs-on: ubuntu-latest
    steps:      
      - name: Gets latest created release info
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases/latest
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Release Asset
        uses: houqp/download-release-assets@v1
        with:
          repo: ${{ github.repository }}
          match: "*.aab$"
          rename: "file.aab"
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.fr_06Games.SuiviScolaire
          releaseFiles: "file.aab"
          releaseName: ${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
          track: alpha
